# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc/news.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fgrpc/news.proto\"%\n\x04News\x12\x0c\n\x04\x63ity\x18\x01 \x01(\t\x12\x0f\n\x07summary\x18\x02 \x01(\t\"?\n\x0cNewsResponse\x12\x0c\n\x04\x63ity\x18\x01 \x01(\t\x12\x0f\n\x07summary\x18\x02 \x01(\t\x12\x10\n\x08\x61nalysis\x18\x03 \x01(\t24\n\x0bNewsService\x12%\n\x0bGetAnalysis\x12\x05.News\x1a\r.NewsResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc.news_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NEWS._serialized_start=19
  _NEWS._serialized_end=56
  _NEWSRESPONSE._serialized_start=58
  _NEWSRESPONSE._serialized_end=121
  _NEWSSERVICE._serialized_start=123
  _NEWSSERVICE._serialized_end=175
# @@protoc_insertion_point(module_scope)
