# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import news_pb2 as grpc_dot_news__pb2


class NewsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAnalysis = channel.unary_unary(
                '/NewsService/GetAnalysis',
                request_serializer=grpc_dot_news__pb2.News.SerializeToString,
                response_deserializer=grpc_dot_news__pb2.NewsResponse.FromString,
                )


class NewsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAnalysis(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NewsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAnalysis': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAnalysis,
                    request_deserializer=grpc_dot_news__pb2.News.FromString,
                    response_serializer=grpc_dot_news__pb2.NewsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'NewsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NewsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/NewsService/GetAnalysis',
            grpc_dot_news__pb2.News.SerializeToString,
            grpc_dot_news__pb2.NewsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
